const GAME_CONFIG = Object.freeze({
  NUMBER_OF_CARDS_TWO_PLAYER: 7,
  CANVAS_WIDTH: 600,
  CANVAS_HEIGHT: 600,
  CARD_SIZE: 60,
  RANK_FONT_FAMILY: "25px Arial",
  SUIT_FONT_FAMILY: "35px Arial",
  RANK_Y_OFFSET: 35,
  SUIT_Y_OFFSET: 10,
  RANK_X_OFFSET: 5,
  SUIT_X_OFFSET: 30,
  TURN_INTERVAL: 200,
  CHIP_RADIUS: 12,
});

export default GAME_CONFIG;
