const GAME_CONFIG = Object.freeze({
  NUMBER_OF_CARDS_TWO_PLAYER: 7,
  CANVAS_WIDTH: 600,
  CANVAS_HEIGHT: 600,
  CARD_SIZE: 60,
  TEXT_FONT_FAMILY: "25px Arial",
  TEXT_Y_OFFSET: 30,
  RANK_X_OFFSET: 10,
  SUIT_X_OFFSET: 30,
});

export default GAME_CONFIG;
